---
abstract: 'Finds the executable line numbers in a Perl program given as astring.'
author:
  - 'Rocky Bernstein <rocky@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.32
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: B-CodeLines
provides:
  B::CodeLines:
    file: lib/B/CodeLines.pm
    version: 1.0
requires:
  perl: 5.008008
  version: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 1.0
